# Generated by Django 2.2.1 on 2019-08-07 04:30

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employees1',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('emp_uid', models.CharField(max_length=120, null=True, unique=True)),
                ('first_name', models.CharField(max_length=20, null=True)),
                ('last_name', models.CharField(max_length=25)),
                ('Gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=3, null=True)),
                ('Date_of_birth', models.DateField(blank=True, null=True)),
                ('date_of_join', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('emp_age', models.IntegerField(blank=True, null=True)),
                ('email', models.CharField(max_length=25)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.CharField(max_length=120, null=True)),
                ('updated_by', models.CharField(max_length=120, null=True)),
            ],
            options={
                'db_table': 'employees1',
            },
            managers=[
                ('all_employees', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.IntegerField()),
                ('sname', models.CharField(max_length=120)),
                ('dob', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='departments1',
            fields=[
                ('department_id', models.IntegerField(primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=30)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.CharField(max_length=120, null=True)),
                ('updated_by', models.CharField(max_length=120, null=True)),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='myapp.employees1')),
            ],
            options={
                'db_table': 'departments1',
            },
        ),
    ]
